const apiList = {
    refreshToken: 'refresh-token-api',
    login: 'login/login-user',
    forgotPassword: 'login/login-forgot-password',
    changePassword: 'usermanagement/user-change-password',
    resetPassword: 'login/login-reset-password',
    signUp: 'signup/register-account',
    // sendOTP: 'signup/send-otp',
    sendOTP: 'signup/send-otp-in-mail',
    // verifyOTP: 'signup/user-verify-otp',
    verifyOTP: 'signup/user-verify-email-otp',
    logout: "login/login-out",
    // billing managment
    addCard: 'Billing/billing-add-card-details',
    deleteCard: 'Billing/DeleteCard',
    creditsusedVSRemaining: 'Billing/billing-credit-used',
    cancelSubscription: 'cancel-subscription',
    getCreditUsed: 'Billing/CreditUsageGraph', //Today ,this week,last 7 days,this month,past 30 days,past 3 months,past 6 months,past year,custom date range
    topUpPlans: "Billing/billing-credits-plan",
    getAllCards: "Billing/billing-card-list",
    setAsDefault: "Billing/SetDefaultCard",
    makePayment: "Billing/BuyCredit",
    isCardAdded: "Billing/billing-check-card-added",
    getTransactions: "Billing/billing-transaction-list",
    downloadInvoice: "Billing/billing-transaction-download",
    cancelSubscriptionNumbers: "Billing/billing-user-number-list",
    // number managment
    getLinkedNumbers: "numbermanagement/number-buyed-list",
    linkedNumbersColumnSearch: "numbermanagement/number-buyed-list-column-search",
    searchNumbers: "numbermanagement/number-available",
    buyNumber: "numbermanagement/number-buy",
    assignAgents: "numbermanagement/number-assign-unassign-user",
    linkedNumbersGlobalSearch: "numbermanagement/number-buyed-list-search",
    getAgentsForAssign: "numbermanagement/number-user-list",
    assignAgentsGlobalSearch: "numbermanagement/number-user-list-search",
    getNumberPriceInCountry: "numbermanagement/number-phoneprice",
    sendOtpOnMobile: "numbermanagement/send-otp",
    verifyMobileOtp: "numbermanagement/user-verify-otp",
    releaseNumber: "numbermanagement/number-release",
    // UserManagement
    getUsers: "usermanagement/user-list",
    getNumbers: "usermanagement/user-assigned-customer-list",
    numbersGlobalSearch: "usermanagement​/user-assigned-number-search",
    assignNumbers: "usermanagement/user-assigned-customer",
    removeAgent: "usermanagement/user-delete",
    addAgent: "usermanagement/user-add",
    disableUser: "usermanagement/user-block",
    agentsGlobalSearch: "usermanagement/user-search",
    agentsColumnSearch: "usermanagement/user-management-list-column-search",
    editUserRole: "usermanagement/user-edit-role",
    //profile
    editProfile: 'profile/profile-update',
    getProfile: 'profile/profile-details',
    agentMuteNotification: "profile/profile-mute-notification",
    getAgentsAnalytics: "profile/profile-message-sent-analytics",
    uploadProfilePicture: "profile/profile-upload",
    removeUserProfilePicture: "",
    //analytics
    getAgentsActivity: "analytics/analytics-agent-list",
    getMultilineChartData: "analytics/analytics-line-graph-sms-sent",
    getKpisData: "analytics/analytics-reports-kpi",
    massegesCount: "analytics/analytics-message-sent",
    agentActivityGlobalSearch: "analytics/analytics-agent-search",
    agentActivityColumnSearch: "analytics/analytics-agent-list-column-search",
    profileKpi: "profile/GetProfileReportsKpi",
    //contacts
    getContactList: "contact/contact-list",
    searchContactList: "contact/contact-search",
    addSingleContact: "contact/contact-add",
    editContact: "contact/contact-update",
    deleteContact: "contact/contact-delete",
    getContactInfo: "contact/contact-details",
    otpOutContact: "contact/contact-optout",
    uploadCSV: "contact/contact-upload-file",
    uploadContactProfilePic: "contact/contact-upload-profile",
    postMappedHeaders: "contact/contact-upload-bulk",
    errorCodes: "contact/contact-error-codes",
    downloadSkipperRecords: "contact/ExportToExcel",
    removeContactProfilePicture: "contact​/contact-upload-profile-delete",
    //chats
    getRecentChats: "Chats/chats-recent-msg-sent-list",
    searchRecentChats: "Chats/chats-recent-msg-sent-list-search",
    getChatHistory: "Chats/chats-history-by-id",
    getCustomerDetails: "Chats/chats-customer-details",
    sendMessage: "WhatsAppSendMsg/send-text",
    replyToMessage: "WhatsAppSendMsg/reply-text",
    sendBulkMessage: "WhatsAppSendMsg/send-bulk-msg",
    sendBulkTemplate: "WhatsAppSendMsg/template-send-bulk-msg",
    //notifications
    getNotifications: "Notification/GetCommonNotificationData",
    markAsRead: "Notification/ChangeNotificationStatus",
    markAllAsRead: "Notification/ChangeAllNotificationStatus",
    deleteNotification: "Notification/DeleteNotififcation",
    deleteAllNotification: "Notification/DeleteAllNotififcation",
    registerSW: "Notification/notification-add-subscription",
    //Segments
    getSegments: "Segment/segment-list",
    deleteSegment: "segment/segment-delete",
    updateSegmentName: "segment/segment-updated-name",
    createSegment: "segment/segment-add",
    getContactsOfSegments: "segment/segment-contact-list",
    contactListForCreateSegment: "segment/segment-contact-list-column-search",
    sendMessageToSegment: "segment/send-sms-to-segment-contacts",
    updateSegmentContacts: "segment/segment-update-contacts",
    sendTemplateToSegment: 'segment/segment-template-send-msg',
    //Auto responder
    createAutoRes: 'autoResponse/autoresponse-add',
    updateAutoRes: 'autoResponse/autoresponse-updated',
    deleteAutoRes: 'autoResponse/autoresponse-delete',
    getAllAutoRes: 'autoResponse/autoresponse-list',
    //post business details
    postBusinessDetails: 'BusinessCredentials/add-business-creditionals',
    enableDisableAutoResponder: 'autoResponse/autoresponder-block',
    //Templates
    templateList: "WhatsApp/get-whatsapp-template-list",
    createTemplate: "WhatsApp/add-template",
    deleteTemplate: "WhatsApp/delete-template",
    sendTemplate: "WhatsAppSendMsg/template-send-msg",
    editTemplate: 'WhatsApp/edit-template',
    enableDisableTemplate: "WhatsAppSendMsg/disable-templates"
};

export { apiList };
